// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: gems.proto

package gems_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TierraClient is the client API for Tierra service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TierraClient interface {
	SolicitarM(ctx context.Context, in *Solicitud, opts ...grpc.CallOption) (*Respuesta, error)
}

type tierraClient struct {
	cc grpc.ClientConnInterface
}

func NewTierraClient(cc grpc.ClientConnInterface) TierraClient {
	return &tierraClient{cc}
}

func (c *tierraClient) SolicitarM(ctx context.Context, in *Solicitud, opts ...grpc.CallOption) (*Respuesta, error) {
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, "/Tierra/SolicitarM", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TierraServer is the server API for Tierra service.
// All implementations must embed UnimplementedTierraServer
// for forward compatibility
type TierraServer interface {
	SolicitarM(context.Context, *Solicitud) (*Respuesta, error)
	mustEmbedUnimplementedTierraServer()
}

// UnimplementedTierraServer must be embedded to have forward compatible implementations.
type UnimplementedTierraServer struct {
}

func (UnimplementedTierraServer) SolicitarM(context.Context, *Solicitud) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitarM not implemented")
}
func (UnimplementedTierraServer) mustEmbedUnimplementedTierraServer() {}

// UnsafeTierraServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TierraServer will
// result in compilation errors.
type UnsafeTierraServer interface {
	mustEmbedUnimplementedTierraServer()
}

func RegisterTierraServer(s grpc.ServiceRegistrar, srv TierraServer) {
	s.RegisterService(&Tierra_ServiceDesc, srv)
}

func _Tierra_SolicitarM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solicitud)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TierraServer).SolicitarM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Tierra/SolicitarM",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TierraServer).SolicitarM(ctx, req.(*Solicitud))
	}
	return interceptor(ctx, in, info, handler)
}

// Tierra_ServiceDesc is the grpc.ServiceDesc for Tierra service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tierra_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Tierra",
	HandlerType: (*TierraServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SolicitarM",
			Handler:    _Tierra_SolicitarM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gems.proto",
}
